// <auto-generated />
namespace Bilinguals.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addImageTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addImageTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202110100829472_addImageTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
